config/routes.rb
Vsouza::Application.routes.draw do
  resources :posts do
	resources :comments
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :autor, :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :conteudo, :nome, :titulo
  
  validates :nome,	:presence => true
  validates :titulo,	:presence => true,
			:length => { :minimum => 5}
  has_many  :comments,  :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  # GET /posts.xml
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.xml  { render xml: @posts  }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
      format.xml  { render xml: @post  }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
      format.xml  { render xml: @post  }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
        format.xml  { render xml: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.xml  { render xml: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
        format.xml { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.xml { render xml: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
      format.xml { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p>
  <b>Autor:</b>
  <%= comment.autor %>
</p>
 
<p>
  <b>Comentario:</b>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Apagar', [comment.post, comment],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label "Autor" %><br />
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label "Comentario" %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit " Adicionar " %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "Meu Blog", posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Blog Rails Application</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tags %>
</head>
<body style="background: #EEEEEE;">

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nome" %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label "Titulo" %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label "Conteudo" %><br />
    <%= f.text_area :conteudo %>
  </div>
  <div class="actions">
    <%= f.submit :value => " Salvar "  %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editando</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @post %> |
<%= link_to 'Voltar', posts_path %>

app/views/posts/index.html.erb
<h1>Postagens</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Titulo</th>
    <th>Conteudo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.nome %></td>
    <td><%= post.titulo %></td>
    <td><%= post.conteudo %></td>
    <td><%= link_to 'Visualizar', post %></td>
    <td><%= link_to 'Alterar', edit_post_path(post) %></td>
    <td><%= link_to 'Excluir', post, :confirm => 'Voce tem certeza?',
                                     :method => :delete %></td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo', new_post_path %>

app/views/posts/new.html.erb
<h1>Nova Postagem</h1>

<%= render 'form' %>

<%= link_to 'Voltar', posts_path %>

app/views/posts/show.html.erb
<p id="notice">
  <%= notice %>
</p>

<p>
  <b>Nome:</b>
  <%= @post.nome %>
</p>

<p>
  <b>Titulo:</b>
  <%= @post.titulo %>
</p>

<p>
  <b>Conteudo:</b>
  <%= @post.conteudo %>
</p>

<h2>Comentarios</h2>
<%= render @post.comments %>

<h2> Comentar:</h2>
<%= render "comments/form" %>

<br />

<%= link_to 'Alterar', edit_post_path(@post) %> |
<%= link_to 'Voltar', posts_path %>